### ISSUE TITLE
Unable to Pass Header Parameters?

### ISSUE THREAD

**Issue by AdminAC** [googlesamples/apps-script-oauth1#1]
Am I doing something wrong?

TypeError: Cannot call method "toUpperCase" of undefined. (line 132, file "Signer", project "OAuth1")

when running the following line:

var response = service.fetch(url, { headers : { "Accept" : "application/json" } });

Removing the headers parameter runs fine, but returns the wrong datatype for my needs.

**Comment by erickoledadevrel** [comment]
There was a bug with how I was initializing parameters. It's fixed now, if you update to the latest version of the library.

**Comment by AdminAC** [comment]
Thank you
