### ISSUE TITLE
Ampersands breaking encoding

### ISSUE THREAD

**Issue by zachwhalen** [googlesamples/apps-script-oauth1#14]
Hi,

I'm using this in the context of a twitter bot, and I've found what I think is a bug. (I could be wrong, though.) What's happening is that when the payload (status=urlencodedtweet) includes and ampersand, the library treats that ampersand as the beginning of a new tweet. 

I'm not sure, but I think this happens <a href="https://github.com/googlesamples/apps-script-oauth1/blob/master/Signer.gs#L194">here</a>, where the deParam function on the Signer decodes it first and then splits it on '&'. Seems to me that it should split it on '&' *before* decoding it, but I haven't been able to test this theory. 

For now, at least, the buggy behavior seems to be consistent: that using an ampersand in a tweet causes part of the payload to get dropped.

Any suggestions?

Thanks,
Zach

**Comment by erickoledadevrel** [comment]
I tried to replicate the problem using my Twitter sample but ampersands were sent along just fine:

https://github.com/googlesamples/apps-script-oauth1/blob/master/samples/Twitter.gs

Are you doing anything different than that?

**Comment by zachwhalen** [comment]
I am doing a few things differently as legacies to older workarounds, but it's good to see a working example. I'll try to bring mine more in line with your sample code and see if that clears it. 

The main differences that stand out are that I'm using an enhanced encodeURIComponent function to also encode reserved characters like (,),!,*, etc., and then I'm setting `escaping` to `false` in the payload object. Let me see if either those make a difference.

**Comment by zachwhalen** [comment]
Ah yes, I see now. I was sending the payload as a string, like "status=some%20status%20with%20percent%20encoding", but I see now that the library expects the payload to be an object, like "status: 'some status message without encoding'".

Obviously, the object method is much simpler, and more importantly, it works. Did this change at some point?

**Comment by erickoledadevrel** [comment]
The escaping behavior was changed in [this commit](https://github.com/googlesamples/apps-script-oauth1/commit/5b3e324cada51b252844b4835e0e56863ef273ba). The problem I'm seeing now is that it's not checking to see if escaping is already disabled, in which case I shouldn't be escaping it again. I'll make a change to fix that.

**Comment by zachwhalen** [comment]
Cool; that makes sense! Thanks.
