### ISSUE TITLE
Partner API requires null token and token secret

### ISSUE THREAD

**Issue by way2go** [googlesamples/apps-script-oauth1#16]
We are working with a partner and were just provided with a consumer and consumer secret, no additional authorization was required. Our existing connection is using OAuthBase and we generate a signature with a null token and token secret and send the request. Is it possible to save a null token with service.saveToken_ and bypass the initial authorization process since we are already authorized?

**Comment by erickoledadevrel** [comment]
Have you tried it?

**Comment by way2go** [comment]
I wasn't quite sure how to use saveToken_ directly but I finally got it working.

```javascript
  var service = getService();
  service.saveToken_({
    public: null,
    secret: null,
    type: 'access'
  });
```
