### ISSUE TITLE
Library not able to connect to Xero

### ISSUE THREAD

**Issue by lahoreia** [googlesamples/apps-script-oauth1#19]
While trying to establish an OAuth 1.0a based connection to Xero I am stuck. Would really appreciate if you could look into the issue.

Here is how my getService() function looks like:
  
 ```
  var service = OAuth1.createService('xero');
  service.setAccessTokenUrl('https:­//a­pi.x­er­o.c­om/­oau­th/­Acc­ess­Token');
  service.setRequestTokenUrl('https://api.xero.com/oauth/RequestToken');
  service.setAuthorizationUrl('https://api.xero.com/oauth/Authorize');
  service.setConsumerKey(CONSUMER_KEY);
  service.setConsumerSecret(CONSUMER_SECRET);
  service.setProjectKey(PROJECT_KEY);
  service.setCallbackFunction('authCallback');
  service.setPropertyStore(PropertiesService.getScriptProperties());
```

I get an error when I do a ``` service.hasaccess() ```

The error shown is:
Error starting OAuth flow: oauth_problem=xero_unknown_error&oauth_problem_advice=could%20not%20generate%20a%20request%20token (line 330, file "Service", project "OAuth1")

Any help would be highly appreciated

**Comment by erickoledadevrel** [comment]
According to their documentation, this error indicates an unknown error on their side:

http://developer.xero.com/documentation/getting-started/oauth-issues/

Can you try again?

**Comment by lahoreia** [comment]
After some research, I figured out that they require a 3 legged OAuth flow

http://developer.xero.com/documentation/getting-started/public-applications/

I guess, this library does not support that yet

**Comment by erickoledadevrel** [comment]
This library does support the 3-legged OAuth flow (it's the default).

**Comment by ZanGOlie** [comment]
I encountered a similar problem that was cased by callback URLs being limited to no more than 250 characters long.

This can be overcome in a similar fashion to what was shown in the [Etsy sample](https://github.com/googlesamples/apps-script-oauth1/blob/master/samples/Etsy.gs) by publishing the script as a web app and overriding the callback url method to use the web app URL.
