### ISSUE TITLE
oauth1 - Twitter: I cannot get Friendship_Lookup functioning...Could not authenticate you

### ISSUE THREAD

**Issue by Iwanjka** [googlesamples/apps-script-oauth1#20]
I am migrating towards the github oauth1 google script class specification. I got the call working for posting, but I get an error when trying to get it functioning with friendship_lookup.

Error: "Request failed for https://api.twitter.com/1.1/friendships/lookup.json returned code 401. Truncated server response: {"errors":[{"code":32,"message":"Could not authenticate you."}]} (use muteHttpExceptions option to examine full response) (line 423, file "Service", project "OAuth1")"

Question: is it possible to post example code for friendships lookup, which I can copy?

THANK YOU!
(Debugging, trying, analyzing took already over 15 hours... hope you, or somebody can help!)

iwanjka@gmail.com

Code:

function friendship_lookUpTest_ITryConformGithubOauth1spec() {
  var service = getService();
  if (service.hasAccess()) {
    var url = 'https://api.twitter.com/1.1/friendships/lookup.json';
    var payload = {
      screen_name: 'twitterapi'
    };
    var response = service.fetch(url, {
      method: 'GET',  
      payload: payload
    });
    var result = JSON.parse(response.getContentText());
    Logger.log(JSON.stringify(result, null, 2));
  } else {
    var authorizationUrl = service.authorize();
    Logger.log('Open the following URL and re-run the script: %s',
        authorizationUrl);
  }
}

**Comment by erickoledadevrel** [comment]
GET requests don't have a payload. The payload value is ignored by the underlying `UrlFetchApp`, but it's content is being used when calculating the OAuth signature. Instead, pass values in the URL query string:

    var url = 'https://api.twitter.com/1.1/friendships/lookup.json?screen_name=twitterapi';
