### ISSUE TITLE
Using multiple instances from Google Sheets

### ISSUE THREAD

**Issue by synbyte** [googlesamples/apps-script-oauth1#23]
Hi,

Please do bear with me, my knowledge of Javascript is virtually non-existent.

I also understand this may not be an issue, but more of a support request (providing what I want to achieve is easy enough with the current codebase).

I'm trying something like the following in order to be able to see multiple follower accounts across my various Tumblr blogs on my sheet. Is there a different (easier?) way of doing this? Is this something that can be made easier in the future? Am I having a "senior moment"?

Everything goes as planned, until it hits the callback and then complains about the CONSUMER_KEY not being set.

Any help is appreciated. Thanks.

```javascript
function getTumblrFollowerCount(id) {
  var setupCredentials = function() {
    if(id == 'notarealaccount.tumblr.com') {
      CONSUMER_KEY = '...';
      CONSUMER_SECRET = '...';
    }
  }
  setupCredentials();
  return getActualTumblrFollowerCount(id);
}

function getActualTumblrFollowerCount(id) {
  var service = getTumblrService();
  if (service.hasAccess()) {
    var response = service.fetch('https://api.tumblr.com/v2/blog/' + id + '/followers');
    var followers = JSON.parse(response);
    return parseFloat(followers.response.total_users); 
  } else {
    var authorizationUrl = service.authorize();
    return authorizationUrl;
  }
}

function tumblrReset() {
  var service = getTumblrService();
  service.reset();
}

function getTumblrService() {
  return OAuth1.createService('tumblr')
      .setAccessTokenUrl('http://www.tumblr.com/oauth/access_token')
      .setRequestTokenUrl('http://www.tumblr.com/oauth/request_token')
      .setAuthorizationUrl('http://www.tumblr.com/oauth/authorize')
      .setConsumerKey(CONSUMER_KEY)
      .setConsumerSecret(CONSUMER_SECRET)
      .setCallbackFunction('tumblrAuthCallback')
      .setPropertyStore(PropertiesService.getUserProperties());
}

function tumblrAuthCallback(request) {
  var service = getTumblrService();
  var authorized = service.handleCallback(request);
  if (authorized) {
    return HtmlService.createHtmlOutput('Success!');
  } else {
    return HtmlService.createHtmlOutput('Denied');
  }
}
```

**Comment by erickoledadevrel** [comment]
The problem is that you are setting CONSUMER_KEY in getTumblrFollowerCount(), which only gets run the first time you start the flow. When tumblrAuthCallback() is called it's a new script execution, so old variables that were set, like CONSUMER_KEY, are not blank.

Like in the samples, set the key and secret outside of any functions, so that they are set on every execution.

**Comment by synbyte** [comment]
So how would I go about setting this up for multiple accounts?

**Comment by erickoledadevrel** [comment]
You can use the same key and secret for multiple accounts, since they are tied to the developer, not the blog. Instead, just use a different service name for each blog:

    getTumblrService(blog_id) {
      return OAuth1.createService(blog_id)
      ...

In your `tumblrAuthCallback()` method, read the service name from the request and load that service:

    function tumblrAuthCallback(request) {
      var blog_id = request.parameter.serviceName;
      var service = getTumblrService(blog_id);
      ...
