### ISSUE TITLE
Error starting OAuth flow on Trello

### ISSUE THREAD

**Issue by mlinaje** [googlesamples/apps-script-oauth1#24]
Using the provided code, importing the library (as resource) and updating CONSUMER_KEY and CONSUMER_SECRET give me this error.
Error starting OAuth flow: {} (línea 330, archivo "Service", proyecto "OAuth1")
Any idea what is happening? Using URL with tokens boards in JSON are returned fine.
Thanks!

**Comment by erickoledadevrel** [comment]
An error response is being returned by the Trello API, but no error message is being returned. I just re-ran the sample and it's working fine for me. Please double check that you have your keys correct and try running reset() to make sure you have a blank slate.
