### ISSUE TITLE
oauth_callback missing

### ISSUE THREAD

**Issue by kristijanPetr** [googlesamples/apps-script-oauth1#25]
Hi, 
I've fetched the latest version from here and when I try to connect to Xing api (https://dev.xing.com)
with oAuth 1.0 , I get the error below
------------------------------------------------------------------------------------------------------------------------
Error starting OAuth flow: {"message":"Required parameter oauth_callback missing","error_name":"REQUIRED_PARAMETER_MISSING"} (line 330, file "Service", project "OAuth1")
------------------------------------------------------------------------------------------------------------------------
I haven't modified the code just changed from 1.0a to 1.0 Oauth protocol ( .setOAuthVersion('1.0') )

**Comment by erickoledadevrel** [comment]
It appears that the API is using OAuth 1.0a, contrary to their documentation. During testing I found there was a bug with the library, but I've just pushed a fix. I've also added a Xing sample, to get you started:

https://github.com/googlesamples/apps-script-oauth1/blob/master/samples/Xing.gs
