### ISSUE TITLE
QuickBooks error when querying with =

### ISSUE THREAD

**Issue by michaes** [googlesamples/apps-script-oauth1#27]
I see this error happening with QuickBooks when querying with =  (%3D)

For the URL https://quickbooks.api.intuit.com/v3/company/123145856926847/reports/ProfitAndLoss?accounting_period%3D'Cash'

I get the below error 
Status : 401.0, 
Response : "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n\n \n \n message=ApplicationAuthenticationFailed; errorCode=003200; statusCode=401\n \n \n\n"

I am blocked with this, appreciate if you could help me to resolve this issue.
thanks

Note : I saw a related issue closed earlier, however I still get this issue in the latest version (13)

**Comment by erickoledadevrel** [comment]
Just pushed out a fix for this. Please updated to version 14 and try again.
