### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by Chinafreak** [googlesamples/apps-script-oauth1#29]
Its look that this isn't working anymore:

`{"errors":[{"code":215,"message":"Bad Authentication data."}]}`

Its say something at lines 433 at file "Service"

It was working before fine (~ 2 years ago), but now not anymore. I'm using for Twitter btw.

**Comment by erickoledadevrel** [comment]
The code still works fine for me. Try resetting the service and authorizing it again.
