### ISSUE TITLE
Support for Standalone Google Apps Script Projects

### ISSUE THREAD

**Issue by xd1936** [googlesamples/apps-script-oauth1#33]
Being able to create sidebars is all well and good when your script is tied to a Document, but what about those of us who want to use Apps Script to interact with OAuth Services in standalone Apps Script projects? We can't call things like `DocumentApp.getUi().showSidebar(page);`.

**Comment by erickoledadevrel** [comment]
Unfortunately there is no way for scripts to manipulate the UI of the script editor. You can either log a message with the URL to open (like the samples do) or publish the script as a web app.
