### ISSUE TITLE
how to change signature method?

### ISSUE THREAD

**Issue by wivaku** [googlesamples/apps-script-oauth1#4]
In Signer.gs I see a reference to signature_method (line 48), how do I set this value (in my case to: PLAINTEXT) when using the library?

**Comment by erickoledadevrel** [comment]
The library currently doesn't expose that option, but it should be fairly easy to create a setter and pass it through. Out of curiosity, which API uses PLAINTEXT signatures?

**Comment by wivaku** [comment]
That would be great Erick. The API: http://www.freshbooks.com/developers/authentication
> Because all requests must use SSL, only the PLAINTEXT signature method is supported.

**Comment by lordscarlet** [comment]
I need RSA-SHA1 for Jira. 

https://developer.atlassian.com/jiradev/api-reference/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-oauth-authentication

**Comment by erickoledadevrel** [comment]
I've added support for PLAINTEXT, but unfortunately RSA isn't supported in Apps Script and therefore won't be possible/feasible in this library.
