### ISSUE TITLE
Certain characters in twitter status break authentication

### ISSUE THREAD

**Issue by zachwhalen** [googlesamples/apps-script-oauth1#5]
Hello,

I'm attempting to use this library to update Twitter, sort of like in the example code. It works most of the time, *unless* the status body contains certain characters: !, *, (, ), and a handful of others. Whereas it works normally without those characters, attempting to send a tweet with an exclamation point cause Twitter to return its error code "32", "Could not authenticate you."

This may be the same underlying problem discussed but never addressed in this Issue: https://code.google.com/p/google-apps-script-issues/issues/detail?id=3046 So it's possible that the solution may lie deeper than this library, but I thought I'd bring it up here just in case.

I've tried various workarounds like replacing ! with %21 in the url string, but all to no avail. Any suggestions? I can provide sample code to reproduce if necessary.

Thanks,
Zach

**Comment by jptrsn** [comment]
You need to percent encode the status, and include the encoding: false
parameter in the post body.

**Comment by zachwhalen** [comment]
You mean like in the options array pasted to service.fetch ? I tried this (example below) and still get the same error:

``` javascript
var status = 'https://api.twitter.com/1.1/statuses/update.json?status=This%20what%21'
var options =
    {
    "method": "POST",
    "muteHttpExceptions": false,
    "encoding" : false
    };
try {
    var result = service.fetch(status, options);
    Logger.log(result.getContentText());    
  }  
catch (e) {
    Logger.log(e.toString());
}

 ```

**Comment by jptrsn** [comment]
Check that the percent encoding is working properly. There are some special
characters that can be passed without a problem, while others will cause
problems and need to be percent encoded. For example, you can't pass !, *,
( or ).

I'm going by memory, since it's been a few months since I grappled with
this. I posted to G+ about it, here's the link.
https://plus.google.com/+JamesPetersen02/posts/7xnheyidqRM

**Comment by zachwhalen** [comment]
This worked! Wow, thanks. The important parameter to set false is "escaping" not "encoding."

Awesome.
