### ISSUE TITLE
Callback url length exceeds its maximum size?

### ISSUE THREAD

**Issue by simonbromberg** [googlesamples/apps-script-oauth1#8]
Trying to use for Fitbit OAuth1.0 because my script stopped working presumably because Google is suspending OAuth1.0 support. 

Error starting OAuth flow:
HTTP Status 400 - Callback url length (399) exceeds its maximum size 255
 (line 299, file "Service", project "OAuth1")

Tried to follow the steps in the readme but I am not sure if I did them correctly. When I authorized originally it didn't seem to ask for the google callback url mentioned in the readme.

```
function getFitbitService() {
  return OAuth1.createService(identifier)
  // Set the endpoint URLs.
  .setAccessTokenUrl("https://api.fitbit.com/oauth/access_token")
  .setRequestTokenUrl("https://api.fitbit.com/oauth/request_token")
  .setAuthorizationUrl("https://api.fitbit.com/oauth/authorize")

  // Set the consumer key and secret.
  .setConsumerKey(getConsumerKey())
  .setConsumerSecret(getConsumerSecret())

  // Set the project key of the script using this library.
  .setProjectKey(projectKey)


  // Set the name of the callback function in the script referenced
  // above that should be invoked to complete the OAuth flow.
  .setCallbackFunction('authCallback')

  // Set the property store where authorized tokens should be persisted.
  .setPropertyStore(PropertiesService.getUserProperties());
 }
 function showSidebar() {
  var fitbitService = getFitbitService();

   if (!fitbitService.hasAccess()) {
       var authorizationUrl = fitbitService.authorize();
       Logger.log(authorizationUrl);
       var template = HtmlService.createTemplate(
    '<a href="<?= authorizationUrl ?>" target="_blank">Authorize</a>. ' +
    'Reopen the sidebar when the authorization is complete.');
       template.authorizationUrl = authorizationUrl;
       var page = template.evaluate();
       DocumentApp.getUi().showSidebar(page);
     } else {
     }
   }

   function authCallback(request) {
     var fitbitService = getFitbitService();
     var isAuthorized = fitbitService.handleCallback(request);
     if (isAuthorized) {
return HtmlService.createHtmlOutput('Success! You can close this tab.');
     } else {
       return HtmlService.createHtmlOutput('Denied. You can close this tab');
     }
   }

   function authorizeForReal() {
      var options =
       {
           "oAuthServiceName": identifier,
           "oAuthUseToken": "always",
       };

     var fitbitService = getFitbitService();
     var response = fitbitService.fetch("https://api.fitbit.com/1/user/-/profile.json",options);
     var o = Utilities.jsonParse(result.getContentText());
     return o.user;
   }
```

**Comment by erickoledadevrel** [comment]
Unfortunately the length of the callback URL cannot be changed, as the state token is needed in order to route the callback correctly. I'll talk with the Apps Script engineering team to see if there is any way we can compress the state tokens more.

**Comment by simonbromberg** [comment]
So my code is ok? Is Fitbit providing the callback URL?

**Comment by erickoledadevrel** [comment]
Your code is fine. This library is creating the callback URL, but unfortunately there is currently no way to make it smaller but still have work in Apps Script.

**Comment by erickoledadevrel** [comment]
Note that FitBit just released OAuth2 support:

https://community.fitbit.com/t5/Web-API/OAuth-2-0-beta-is-here/m-p/778224#U778224

The OAuth2 library has been updated to support it:

https://goo.gl/EcddOz

Here's some sample code that shows how to make to use that library with it:

    function fitbitTest() {
      var service = getFitbitService();
      if (service.hasAccess()) {
        var date = new Date();
        date.setDate(date.getDate() - 1);
        var dateStr = Utilities.formatDate(date, Session.getScriptTimeZone(), 'yyyy-MM-dd');
        var url = 'https://api.fitbit.com/1/user/-/activities/date/' + dateStr + '.json';
        var response = UrlFetchApp.fetch(url, {
          headers: {
            'Authorization': 'Bearer ' + service.getAccessToken()
          }
        });
        Logger.log(JSON.stringify(JSON.parse(response.getContentText()), null, 2));
      } else {
        var authUrl = service.getAuthorizationUrl();
        Logger.log('Visit this url: ' + authUrl);
      }
    }

    function getFitbitService() {
      var clientId = '...';
      var clientSecret = '...';
      return OAuth2.createService('fitbit')
          .setAuthorizationBaseUrl('https://www.fitbit.com/oauth2/authorize')
          .setTokenUrl('https://api.fitbit.com/oauth2/token')
          .setClientId(clientId)
          .setClientSecret(clientSecret)
          .setProjectKey('...')
          .setCallbackFunction('fitbitAuthCallback')
          .setPropertyStore(PropertiesService.getUserProperties())
          .setScope('activity')
          .setTokenHeaders({
            'Authorization': 'Basic ' + Utilities.base64Encode(clientId + ':' + clientSecret)
          });
    }

    function fitbitAuthCallback(request) {
      try {
        var service = getFitbitService();
        var authorized = service.handleCallback(request);
        if (authorized) {
          return HtmlService.createHtmlOutput('Success! You can close this tab.');
        } else {
          return HtmlService.createHtmlOutput('Denied. You can close this tab');
        }
      } catch (e) {
        return HtmlService.createHtmlOutput('Error: ' + e);
      }
    }

I'll leave this issue open however, since they may be other APIs that run into the URL length issue.

**Comment by simonbromberg** [comment]
Thanks

It actually started working again a day or two later, so not really sure what the problem was.

**Comment by GGPay** [comment]
Hi Eric,
Thanks for library. 
Is this issue has been resolved? I have the same error trying to use for Etsy.

**Comment by erickoledadevrel** [comment]
A work around we can use for APIs that only support 255 character callback URLs is to publish the script as a web app, and use that URL instead of the `/usercallback` URL. I published an Etsy sample that does that:

https://github.com/googlesamples/apps-script-oauth1/blob/master/samples/Etsy.gs
